stages:
  - check
  - build staging
  - deploy staging
  - test staging
  - build prod
  - deploy prod

check:
  stage: check
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  script:
    - sonar-scanner -X -Dproject.settings=$SONAR_PROPERTIES
  allow_failure: false
  only:
    refs:
      - master
      - backend
  tags:
    - sonarrunner

build staging:
  stage: build staging
  environment: staging
  before_script:
    - sudo docker login -u $REGISTRY_USER -p $REGISTRY_PASS https://dockregistry.bm.co.id
  script:
    - cp $ENV_BE .env
    - sudo docker build -f docker/Dockerfile -t dockregistry.bm.co.id/bimasakti/saas-travel-backend:staging-latest .
    - sudo docker push dockregistry.bm.co.id/bimasakti/saas-travel-backend:staging-latest
  after_script:
    - sudo docker logout dockregistry.bm.co.id
  needs: [check]
  when: on_success
  allow_failure: false
  only:
    refs:
      - master
      - backend
  tags:
    - gitlabrunner01

deploy staging:
  stage: deploy staging
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS https://dockregistry.bm.co.id
  script:
    - docker compose -f docker/docker-compose.yml pull saas-travel-backend-staging
    - docker compose -f docker/docker-compose.yml -p saas-travel-backend-staging up -d saas-travel-backend-staging
  after_script:
    - docker logout dockregistry.bm.co.id
  needs: [check, build staging]
  when: on_success
  allow_failure: false
  only:
    refs:
      - master
      - backend
  tags:
    - fpstaging

test staging:
  stage: test staging
  script:
    - curl 10.9.43.5:8001
  needs: [check, build staging, deploy staging]
  when: on_success
  allow_failure: false
  only:
    refs:
      - master
      - backend
  tags:
    - h2htravel01

build prod:
  stage: build prod
  environment: prod
  before_script:
    - sudo docker login -u $REGISTRY_USER -p $REGISTRY_PASS https://dockregistry.bm.co.id
  script:
    - cp $ENV_BE .env
    - sudo docker build -f docker/Dockerfile -t dockregistry.bm.co.id/bimasakti/saas-travel-backend:latest .
    - sudo docker push dockregistry.bm.co.id/bimasakti/saas-travel-backend:latest
  after_script:
    - sudo docker logout dockregistry.bm.co.id
  needs: [check]
  when: manual
  allow_failure: false
  only:
    refs:
      - master
      - backend
  tags:
    - gitlabrunner01

deploy prod:
  stage: deploy prod
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS https://dockregistry.bm.co.id
  script:
    - docker compose -f docker/docker-compose.yml pull saas-travel-backend
    - docker compose -f docker/docker-compose.yml -p saas-travel-backend up -d saas-travel-backend
  after_script:
    - docker logout dockregistry.bm.co.id
  needs: [check, build prod]
  when: on_success
  allow_failure: false
  only:
    refs:
      - master
      - backend
  tags:
    - h2htravel01
